name       : wpa_supplicant
version    : '2.9'
release    : 21
source     :
    - https://w1.fi/releases/wpa_supplicant-2.9.tar.gz : fcbdee7b4a64bea8177973299c8c824419c413ec2e3a95db63dd6a5dc3541f17
license    : BSD-3-Clause
component  : network.base
summary    : WiFi authentication client and server
description: |
    WPA Supplicant is a Wi-Fi Protected Access (WPA) client and IEEE 802.1X supplicant. It implements WPA key negotiation with a WPA Authenticator and Extensible Authentication Protocol (EAP) authentication with an Authentication Server. In addition, it controls the roaming and IEEE 802.11 authentication/association of the wireless LAN driver. This is useful for connecting to a password protected wireless access point.
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(openssl)
setup      : |
    %apply_patches

    install -m00644 $pkgfiles/config wpa_supplicant/.config
build      : |
    cd wpa_supplicant
    %make BINDIR=/sbin LIBDIR=/lib PREFIX=/usr
install    : |
    cd wpa_supplicant
    %make_install BINDIR=/sbin LIBDIR=/lib PREFIX=/usr

    install -Ddm00755 $installdir/usr/share/dbus-1/system-services
    install -m00644 dbus/*.service $installdir/usr/share/dbus-1/system-services/.
    install -Dm00644 dbus/dbus-wpa_supplicant.conf $installdir/usr/share/dbus-1/system.d/dbus-wpa_supplicant.conf

    install -Ddm00755 $installdir/usr/lib/systemd/system
    install -m00644 systemd/*.service $installdir/usr/lib/systemd/system/.

    install -Dm00755 $pkgfiles/sleep $installdir/usr/lib/systemd/system-sleep/wpa_supplicant.sh
