name       : wpa_supplicant
version    : '2.6'
release    : 10
source     :
    - https://w1.fi/releases/wpa_supplicant-2.6.tar.gz : b4936d34c4e6cdd44954beba74296d964bc2c9668ecaa5255e499636fe2b1450
license    :
    - BSD-3-Clause
summary    : WiFi authentication client and server
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(openssl)
component  : network.base
description: |
    WPA Supplicant is a Wi-Fi Protected Access (WPA) client and IEEE 802.1X supplicant. It implements WPA key negotiation with a WPA Authenticator and Extensible Authentication Protocol (EAP) authentication with an Authentication Server. In addition, it controls the roaming and IEEE 802.11 authentication/association of the wireless LAN driver. This is useful for connecting to a password protected wireless access point.
setup      : |
    %apply_patches
    pushd wpa_supplicant
    install -m 00644 $pkgfiles/config .config
build      : |
    pushd wpa_supplicant
    %make BINDIR=/sbin LIBDIR=/lib PREFIX=/usr
install    : |
    pushd wpa_supplicant
    %make_install BINDIR=/sbin LIBDIR=/lib PREFIX=/usr

    install -D -d -m 00755 $installdir/usr/share/dbus-1/system-services
    install -m 00644 dbus/*.service $installdir/usr/share/dbus-1/system-services/.
    install -D -m 00644 dbus/dbus-wpa_supplicant.conf $installdir/usr/share/dbus-1/system.d/dbus-wpa_supplicant.conf

    install -D -d -m 00755 $installdir/usr/lib/systemd/system
    install -m 00644 systemd/*.service $installdir/usr/lib/systemd/system/.

    install -D -m 00755 $pkgfiles/sleep $installdir/usr/lib/systemd/system-sleep/wpa_supplicant.sh
